### ISSUE TITLE
Allow access to `AbilityFactory`

### ISSUE THREAD

**Issue by andreialecu** [getjerry/nest-casl#198]
I'd like to be able to use [`packRules`](https://casl.js.org/v5/en/api/casl-ability-extra#pack-rules) to share permissions with an Angular front end app.

The following *hack* works:

```ts
	const user = userProxy?.getFromRequest();
    if (user) {
      const abilityFactory: AbilityFactory = (this.accessService as any)
        .abilityFactory;
      console.log(packRules(abilityFactory.createForUser(user).rules));
```

Where `this.accessService` basically hijacks this private field from AccessService: 

https://github.com/getjerry/nest-casl/blob/a3af8364f8da96563f6ae16d9f487725c2631355/src/access.service.ts#L16

Exporting `AbilityFactory`, or an API to get to the underlying `casl` abilities would be great.

**Comment by liquidautumn** [comment]
Yes, this is unacceptable. I'm thinking about handling this specific use case, as it should be quite common. ie `this.accessService.getAbilitiesForUser(user, { pack: true })`. Combined with #202 it'll make lib client code much cleaner.

**Comment by kinglouie** [comment]
@liquidautumn I'm trying to get all rules defined across all modules in my auth module to return the rules on my login route, how do I use `this.accessService.getAbility(user)` to get them? 

As far as I understand when I want to use `accessService` in my auth module, I need to import `CaslModule.forFeature({ permissions})` but because of the expected `permissions` parameter I do not get all defined permissions.

**Comment by Hatzl** [comment]
@kinglouie did you find any solution for that?

**Comment by kinglouie** [comment]
@Hatzl  unfortunately not
